version: '3.8'

services:
  db:
    image: postgres:latest
    container_name: postgres_container
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: lab
    ports:
      - "5434:5434"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    image: openjdk:17-jdk-alpine
    container_name: perfilinga_lab_app
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://localhost:5434/lab
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: password
    ports:
      - "8081:8080"
    depends_on:
      - db

volumes:
  postgres_data:
    driver: local
